server:
  port: 8080

spring:
  application:
    name: edumanage

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eduSYSTEM?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.keshe.edumanage.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: your-secret-key
  expire: 7200000

cas:
  server-url-prefix: http://localhost:8081/cas
  client-service-url: http://localhost:8080/api/auth/cas/callback






logging:
  level:
    com.keshe.edumanage: debug
